ColengoChallenge.App/Controllers/ProductController.cs
using Azure.Core;
using ColengoChallenge.Api.Features.Products;
using ColengoChallenge.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ColengoChallenge.App.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ProductController : ControllerBase
    {
        private readonly IProductRepository ProductRepository;
        public ProductController(IProductRepository aProductRepository)
        {
            ProductRepository = aProductRepository;
        }

        // GET api/product/get-products?page=1&pageSize=10
        [HttpGet("get-products")]
        public async Task<IActionResult> GetProducts([FromQuery] GetProductRequest request)
        {
            // Validate the request parameters
            if (request.Page <= 0)
            {
                return BadRequest();
            }

            if (request.PageSize <= 0)
            {
                return BadRequest();
            }

            // Fetch the products from the repository
            var response = await ProductRepository.GetProducts(request);

            // Return the response as JSON
            return Ok(response);
        }

    }
}

ColengoChallenge.App/Controllers/ProductSyncController.cs
using ColengoChallenge.Api.Features.Products;
using ColengoChallenge.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ColengoChallenge.App.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ProductSyncController : ControllerBase
    {
        private readonly IProductSyncService _productSyncService;

        public ProductSyncController(IProductSyncService productSyncService)
        {
            _productSyncService = productSyncService;
        }


        [HttpGet("start")]
        public async Task<IActionResult> SyncProducts([FromQuery] int page = 1, [FromQuery] int pageSize = 50)
        {
            if (page <= 0 || pageSize <= 0)
            {
                return BadRequest("Page and PageSize must be greater than 0.");
            }

            try
            {
                var request = new GetDemoProductsRequest
                {
                    Page = page,
                    PageSize = pageSize
                };

                await _productSyncService.SyncProductsAsync(request);
                return Ok("Products synchronized successfully.");
            }
            catch (HttpRequestException ex)
            {
                return StatusCode(502, "Bad Gateway: Failed to fetch products.");
            }
            catch (DbUpdateException ex)
            {
                return StatusCode(500, "Internal Server Error: Failed to save products.");
            }
            catch (Exception ex)
            {
                return StatusCode(500, "An unexpected error occurred. Please try again later.");
            }
        }

    }
}

ColengoChallenge.App/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ColengoChallenge.App.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

ColengoChallenge.App/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ColengoChallenge.App.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ColengoChallenge.App/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ColengoChallenge.App.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

ColengoChallenge.App/Pages/ProductPage.cshtml.cs
using ColengoChallenge.Api.Dto;
using ColengoChallenge.Api.Features.Products;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace ColengoChallenge.App.Views.Product
{
    public class ProductPageModel : PageModel
    {
        private readonly HttpClient _httpClient;

        public ProductPageModel(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public List<ProductDto> Products { get; set; } = new List<ProductDto>();
        public int TotalPages { get; set; }
        public int CurrentPage { get; set; } = 1;
        public int PageSize { get; set; } = 10;

        public async Task OnGetAsync(int page = 1)
        {
            CurrentPage = page;
            await LoadProducts();
        }

        public async Task LoadProducts()
        {
            var requestUrl = $"https://localhost:7193/api/product/get-products?page={CurrentPage}&pageSize={PageSize}";

            var response = await _httpClient.GetAsync(requestUrl);
            if (response.IsSuccessStatusCode)
            {
                var jsonResponse = await response.Content.ReadAsStringAsync();
                var result = JsonSerializer.Deserialize<GetProductResponse>(jsonResponse, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });

                Products = result.Products;
                TotalPages = result.TotalPages;
            }
        }

        public async Task<IActionResult> OnGetChangePage(int page)
        {
            CurrentPage = page;
            await LoadProducts(); // Reload products for the selected page
            return Page();
        }
    }
}

ColengoChallenge.App/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ColengoChallenge.App/Pages/ProductPage.cshtml
@page "/products"
@model ColengoChallenge.App.Views.Product.ProductPageModel
@{
    ViewData["Title"] = "Product List";
}

<div class="px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
            <h1 class="text-base font-semibold leading-6 text-gray-900">Products</h1>
            <p class="mt-2 text-sm text-gray-700">A list of all products including their name, price, and image.</p>
        </div>
    </div>
    <div class="mt-8 flow-root">
        <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                <table class="min-w-full divide-y divide-gray-300">
                    <thead>
                        <tr>
                            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Images</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Title</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Price</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-200">
                        @foreach (var product in Model.Products)
                        {
                            <tr>
                                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                                    <img src="@product.ThumbnailImage" alt="Product Image" />
                                </td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                                    @product.Name
                                </td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                                    @product.Price.Amount
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <!-- Pagination -->
            <div class="flex items-center justify-between border-t border-gray-200 bg-white px-4 py-3 sm:px-6">
                <div class="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
                    <div>
                        <p class="text-sm text-gray-700">
                            Showing
                            <span class="font-medium">@Model.CurrentPage</span>
                            to
                            <span class="font-medium">@Model.PageSize</span>
                            of
                            <span class="font-medium">@Model.TotalPages</span>
                            results
                        </p>
                    </div>
                    <div>
                        <nav class="isolate inline-flex -space-x-px rounded-md shadow-sm" aria-label="Pagination">
                            @for (int index = 1; index <= Model.TotalPages; index++)
                            {
                                <form method="get" asp-page-handler="ChangePage" asp-route-page="@index" class="inline">
                                    <button type="submit" class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">
                                        @index
                                    </button>
                                </form>
                            }
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ColengoChallenge.App/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ColengoChallenge.App</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ColengoChallenge.App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ColengoChallenge.App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ColengoChallenge.App - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>